/** Canonical UI strings. Mirror `copy.md` — do not invent a second voice. */

export const copy = {
  brand: {
    name: "Kachis",
    product: "Data Shield",
  },
  input: {
    title: "Original prompt",
    helper: "Paste here. Secrets stay on this machine until you scan and settle.",
    placeholder: "Type or paste payroll, source, contracts, or internal notes…",
    paste: "Paste",
    pasteFailed: "Clipboard paste blocked — use Ctrl+V.",
    sample: "Load payroll sample",
    sampleCode: "Load code & client sample",
    security: "Security filters",
  },
  filters: {
    pii: {
      label: "Strip identifiers",
      tooltip: "Masks emails, phones, SSNs, and similar markers locally.",
    },
    financial: {
      label: "Mask financials",
      tooltip: "Redacts amounts, routing, and account formats.",
    },
    secrets: {
      label: "Hold secrets",
      tooltip: "Blocks API keys, JWTs, and private key material locally.",
    },
    code: {
      label: "Insulate source",
      tooltip: "Redacts env assignments, code secrets, and internal paths.",
    },
    client: {
      label: "Strip client records",
      tooltip: "Masks labeled customer, account, and opportunity lines.",
    },
  },
  pack: {
    required:
      "Institutional workspaces must enable every filter before scan.",
    labels: {
      pii: "Identifiers",
      financial: "Financials",
      secrets: "Secrets",
      code: "Source",
      client: "Client",
    },
  },
  action: {
    idle: "Run Kachis Scanner",
    processing: "Scanning locally…",
    success: "Shielded",
    error: "Verification failed",
    scanning: "Scanning locally…",
    rewriting: "Insulating prompt…",
    guarding: "Insulating prompt…",
    proving: "Waiting for wallet…",
    attesting: "Recording settlement…",
    walletRequired: "Connect wallet to settle",
    walletRequiredHint: "Connect your wallet before you approve & settle the shield.",
    fundRequired: "Fund fee reserve to settle",
    fundRequiredHint:
      "Settlement needs a positive fee reserve. Faucet tNIGHT, wait for tDUST, then refresh balances. On Gero, exact tDUST may only appear in the wallet dashboard.",
    geroSettleHint:
      "Gero can connect and prove, but cannot balance contract settlements yet. Use 1AM to Approve & Settle.",
    geroBalanceUnsupported:
      "Gero cannot balance contract settlements yet. Connect 1AM with a funded fee reserve to settle.",
    proofServerUnreachable:
      "Proof server unreachable. Use 1AM (in-wallet proving), or start a local proof server on :6300 for Lace.",
    settleFailed: "Settlement did not complete. Nothing was recorded.",
    walletRejected: "Wallet request declined. Approve in your wallet to settle the shield.",
    reconnectWallet: "Wallet session expired. Disconnect and connect 1AM again, then retry.",
    settleBundleFailed:
      "Settle bundle failed to load. Stop the server and run npm run dev (webpack), then hard-refresh and reconnect 1AM.",
    privateStateCorrupt:
      "Stale local keys blocked settle. Close other localhost tabs, hard-refresh, reconnect 1AM, and settle again.",
    toastScanReady: "Prompt insulated",
    toastScanReadyBody: "Review the shielded text, then approve & settle.",
    toastSettlePending: "Waiting for wallet approval…",
    toastSettleOk: "Shield settled",
    toastSettleOkBody: "Receipt recorded. Confirm & send when ready.",
    toastSettleErr: "Settlement blocked",
    toastSendOk: "Sent to model",
    toastSendErr: "Send failed",
    toastPackRequired: "Enable required filters",
  },
  status: {
    shielded: "Shielded",
    pipeline: "Zero-leak path active",
    unverified: "Wallet not connected",
    localReview: "Local sandbox review — data insulated on-device",
  },
  sanitized: {
    title: "Shielded prompt",
    helper: "Watch the local rewrite, settle the shield, then send the insulated text.",
    empty: "Waiting for scanner",
    emptyHint: "Run Kachis Scanner on the left. The insulated prompt appears here word by word.",
    settle: "Approve & Settle Shield",
    settling: "Waiting for wallet…",
    confirmSend: "Confirm & Send",
    sending: "Sending…",
    sent: "Sent",
    receiptTitle: "Settlement receipt",
    receiptHash: "Commitment",
    receiptTx: "Settlement id",
    receiptLedger: "Public id",
    receiptReady: "Pack attested. Review, then send.",
  },
  response: {
    title: "Response",
    helper: "The model reply based on the shielded prompt.",
    empty: "No response yet",
    emptyHint: "Confirm & Send the shielded prompt to generate a reply.",
    emptyBeforeShield: "Scan, settle, and confirm the prompt first. The model reply appears here.",
    waiting: "Waiting for the model…",
    assistantLabel: "Kachis",
    walkthroughLabel: "Walkthrough",
    betaLabel: "Beta · Gemini",
    byocLabel: "BYOC",
    noModel:
      "No model path ready. Use free responses or bring your own compute.",
    error: "Request failed. The shielded prompt was not delivered.",
    fundedQuota: "{remaining}/{limit} free responses left today",
    fundedModel: "Kachis funded · Gemini",
    fundedEmpty: "0/{limit} free responses left today",
    fundedOffline: "Hosted compute offline",
    needMore: "Need more?",
    bringCompute: "Bring your own compute",
    usingByoc: "Using your compute · {provider}",
    manageByoc: "Manage compute",
    clearByoc: "Switch back to Kachis funded",
  },
  chat: {
    // Legacy keys kept for any remaining imports; prefer sanitized / response.
    title: "Response",
    subtitle: "The model only ever sees the shielded prompt.",
    userLabel: "You",
    assistantLabel: "Kachis",
    placeholderLocked: "Shield your prompt first",
    placeholderWallet: "Connect your wallet to continue",
    placeholderOpen: "",
    send: "Confirm & Send",
    emptyLocked: "Waiting for scanner",
    emptyLockedHint: "Run the scanner, settle the shield, then confirm & send.",
    emptyWallet: "Connect your wallet.",
    emptyWalletHint: "Connect on the top right, then settle the shield.",
    emptyFund: "Fee reserve required.",
    emptyFundHint:
      "Faucet tNIGHT, wait for tDUST, refresh balances, then settle the shield.",
    emptyOpen: "Ready to send",
    emptyOpenHint: "Confirm & Send the shielded prompt to the model.",
    useShielded: "Use shielded prompt",
    noModel:
      "No model path ready. Use beta quota or add a BYOC key in Identity for this session.",
    walkthroughLabel: "Walkthrough",
    suggestionShielded: "Confirm & Send",
    suggestionEdit: "Review insulated text",
  },
  demo: {
    nav: "Walkthrough",
    landing: "Walkthrough",
    banner:
      "You are in demo. No wallet or settlement required. Sample paste, local scan, simulated settle, canned reply.",
    loadSample: "Load sample",
    settleNote: "Walkthrough settle. No wallet or Midnight transaction ran.",
    reply:
      "Leak risk: High if this packet left the perimeter unshielded. Identifiers, bank rails, cash figures, and an export key were present in the original paste.\n\nCFO briefing (redacted)\n\n- Packet: Q3 compensation review for the board call\n- Subject: [EMPLOYEE] · [EMAIL] · [PHONE]\n- Tax ID: [SSN]\n- Banking: account [ACCOUNT], routing [ACCOUNT]\n- Comp: bonus [AMOUNT]; salary band [AMOUNT]–[AMOUNT]\n- Secrets: payroll export key removed ([SECRET])\n\nRecommendation: circulate only this insulated summary. Keep the original packet on-device; do not paste raw values into vendor models or shared docs.",
  },
  seat: {
    unbound: "Not connected",
    notConnected: "Not connected",
    verified: "Connected",
  },
  guardrails: {
    liveTitle: "Mandatory filters",
    liveHint:
      "Institutional workspaces must enable every filter before scan. Tenant-persisted policy is later.",
    seatTitle: "Workspace governance",
    seatEmpty: "No wallet connected.",
    seatLive: "Wallet connected. Role policies are later.",
  },
  rail: {
    title: "Local verification path",
    last: "Last verification",
    idle: "No local verification yet",
    ledger: "Public commitment id",
    notaryLocal: "Recorded locally. Connect a funded wallet to settle.",
    notaryServer: "Verification service reachable. Settlement still needs a funded wallet.",
    notarySettled: "Settled. Verification ran; the original stays on this machine.",
    settleFallback:
      "Settlement did not complete. The local commitment is still recorded.",
    tx: "Settlement id",
    network: "Network",
    steps: [
      {
        id: "how-paste",
        title: "Paste internally",
        body: "Source, records, and briefs stay in your sandbox. Nothing is uploaded yet.",
      },
      {
        id: "how-scan",
        title: "Run Kachis Scanner",
        body: "Sensitive spans highlight, then rewrite into insulated placeholders on this machine.",
      },
      {
        id: "how-settle",
        title: "Approve & settle",
        body: "Confirm in your wallet. The receipt proves the pack ran — without revealing the file.",
      },
      {
        id: "how-chat",
        title: "Confirm & send",
        body: "Only the insulated prompt reaches the model. Raw values stay here.",
      },
      {
        id: "how-identity",
        title: "Authenticate the member",
        body: "Corporate credentials prove role and policy without exposing the token.",
      },
    ],
  },
  tiers: {
    sandbox: {
      id: "freelancer" as const,
      pill: "Sandbox",
      badge: "Sandbox Workspace",
      description: "Individual sandbox for secure data parsing.",
      limit:
        "Approaching freelance local limit. Upgrade to an Institutional Network for company-wide custom rules, advanced regex filtering, and security compliance matrices.",
    },
    institutional: {
      id: "institutional" as const,
      pill: "Institutional",
      badge: "Institutional Network",
      description:
        "Enterprise-wide guardrail featuring custom organizational identity roots and granular workspace governance.",
    },
  },
  agent: {
    title: "Autonomous Agent Insulation",
    description:
      "Insulate machine-to-machine workflows. Protect background developer scripts, automated data analysts, and service bots from leaking proprietary records to public endpoints.",
    label: "Automate",
    badge: "SDK Gateway Active",
  },
  wallet: {
    connect: "Connect Wallet",
    verifying: "Connecting...",
    verifiedSuffix: "Organization Verified",
    identity:
      "Identity authenticated via sovereign credentials. Your private roles and cryptographic clearance tokens remain on-device.",
    disconnect: "Disconnect",
    cancel: "Cancel",
    choose: "Connect a wallet. The unshielded address is used for dApp connect.",
    modalTitle: "Connect a Wallet",
    modalEducateTitle: "What is a Wallet?",
    modalEducateAssetsTitle: "A home for your digital assets",
    modalEducateAssetsBody: "Wallets are used to send, receive, store, and display digital assets.",
    modalEducateLoginTitle: "A new way to log in",
    modalEducateLoginBody:
      "Instead of creating new accounts and passwords on every website, just connect your wallet.",
    modalGetWallet: "Get a Wallet",
    modalLearnMore: "Learn More",
    modalRecommended: "Recommended",
    modalComingSoon: "Coming soon",
    modalSupported: "Supported",
    modalDetected: "Detected",
    modalUnavailable: "Install to connect",
    modalEmpty:
      "Install 1AM and unlock it on this page. Other wallets are listed for later settle support.",
    modalApproveHint: "Approve in the wallet pop-up. It may open behind this window.",
    modalComingSoonHint: "Settle support is not ready for this wallet yet.",
    unshielded: "Unshielded",
    shielded: "Shielded",
    dust: "Fee reserve",
    dustExists: "Exists",
    dustCheckWallet: "For exact balance, check your Gero wallet / dashboard.",
    refresh: "Refresh balances",
    balancesUnavailable: "Balances unavailable",
    viewIdentity: "Open AI Providers",
  },
  analytics: {
    leaks: "Leaks mitigated locally",
    secretsHeld: "Sensitive keys held",
    secretsHint: "Secrets filter findings this quarter",
    credentials: "Members verified",
    settlements: "Settlements sealed",
    cycles: "Recent shielded jobs",
    quarterTitle: "This quarter",
    quarterEmpty: "No shields in this quarter yet.",
    quarterSettlements: "Settlements",
    quarterFindings: "Findings held",
    quarterOnChain: "Settled",
    packs: "Filters",
    trailHint:
      "Open Midnight Audit Trail for chronological settlements, commitment hashes, and policy flags.",
  },
  audits: {
    title: "Settlement register",
    helper:
      "Immutable public commitments for this quarter. Original text never appears here.",
    binding: "Binding",
    noPack: "No filters recorded on this settlement.",
  },
  integrations: {
    title: "Install & connect",
    helper:
      "Every integration must call the local shield before a model sees the paste.",
    agentTitle: "Kachis Agent",
    agentBody:
      "Local MCP server for Cursor and Claude Desktop. The host must call kachis_shield before any model sees the paste.",
    agentStatusLive: "Live",
    step1Title: "Install the agent",
    step1Body: "From the agent folder: npm install, then npm start — or let the host start it via MCP.",
    step2Title: "Add the host config",
    step2Body:
      "Paste this into Cursor or Claude Desktop MCP settings. On Windows, set cwd to the full path of the agent folder.",
    step3Title: "Shield before the model",
    step3Body:
      "Host calls kachis_shield on the raw paste, then sends only the shielded prompt to the model. Public commitments post to this console.",
    configLabel: "MCP config",
    copyConfig: "Copy",
    copiedConfig: "Copied",
    toolTitle: "Tool contract",
    toolName: "kachis_shield",
    toolInput: "Raw paste + optional pack toggles. Defaults: all five packs on.",
    toolOutput:
      "Shielded prompt plus public commitments. Original text never leaves the machine.",
    toolRule: "Send only the shielded prompt to the model — never the original paste.",
    activityTitle: "Agent activity",
    activityHelper:
      "Public commitments recorded when the agent reaches this console. Original paste is never stored.",
    activityEmpty:
      "No agent shields recorded yet — start the agent and call kachis_shield.",
    activityHash: "Commitment",
    activityMeta: "Source · status",
    libraryTitle: "Library embed",
    libraryBody:
      "Call runShield from shared/ inside apps and agent runtimes. Same filters as the console — not a separate published package.",
    companionTitle: "Browser companions",
    companionBody: "Extension companions for vendor chat surfaces ship after MCP coverage.",
    statusLater: "Later",
    // Legacy keys kept for any stale imports
    sdkTitle: "Library embed",
    sdkBody:
      "Call runShield from shared/ inside apps and agent runtimes. Same filters as the console.",
    mcpTitle: "Kachis Agent",
    mcpBody: "Kachis Agent exposes kachis_shield for Cursor and Claude Desktop hosts.",
    statusLive: "Live",
  },
  landing: {
    launchApp: "Launch app",
  },
  onboarding: {
    signInTitle: "Sign in to Kachis",
    signInBody: "Connect a wallet to continue.",
    signInHint: "No password. Approve the wallet connection to continue.",
    signedIn: "Wallet connected",
    walletFirst: "Wallet-first access. Your unshielded address becomes your account id.",
    openingWorkspace: "Opening workspace…",
    verifyingAccount: "Checking your account…",
    chooseTitle: "Choose your workspace",
    chooseBody:
      "Solo workspaces stay freemium with optional filters. Institutional networks enforce full policy.",
    soloTitle: "Launch Solo Sandbox",
    soloBody:
      "For freelancers and builders. Optional filters, no forced institutional policy, immediate workspace access.",
    soloCta: "Enter sandbox",
    institutionalTitle: "Provision Institutional Node",
    institutionalBody:
      "For companies. Create an organization, assign the admin, and require every mandatory filter.",
    institutionalCta: "Provision node",
    orgNameHint: "Enter an organization name (at least 2 characters).",
    configureTitle: "Configure workspace",
    configureSoloBody: "Personal Sandbox with optional filters. No institutional policy enforced.",
    configureOrgBody: "Name the organization. You become the admin.",
    finishTitle: "Launch workspace",
    finishSoloBody: "Create your sandbox profile and open the console.",
    finishOrgBody: "Provision the institutional node, then open the console.",
    stepBack: "Previous",
    stepNext: "Next",
    stepComplete: "Launch",
    successSoloTitle: "You're in",
    successSoloBody: "Personal Sandbox is ready. Setting up your workspace next.",
    successOrgTitle: "Organization created",
    successOrgBody: "{name} is live. Setting up your institutional workspace next.",
    setupLoading: [
      { text: "Binding wallet identity" },
      { text: "Applying workspace policy" },
      { text: "Preparing secure console" },
      { text: "Opening workspace" },
    ],
    provisionSteps: [
      "Initializing core keys…",
      "Creating organization…",
      "Syncing with Midnight contract space…",
      "Applying required policy…",
      "Node status: Operational",
    ],
    provisionDone: "Organization ready. Opening console…",
    supabaseMissing:
      "Supabase is not configured. Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY, then run supabase/schema.sql.",
    upgradeTitle: "Institutional Network",
    upgradeBody:
      "Custom filters, organization members, and mandatory policy are available on an institutional node.",
    upgradeCta: "Upgrade workspace",
    locked: "Institutional",
  },
  nav: {
    workspace: "Workspace",
    security: "Security & Evidence",
    settings: "Settings",
    contextLabel: "Organization",
    sandbox: "Personal Sandbox",
    institutional: "Institutional Network",
    orgSuffix: "Network",
    connectHint: "Connect a wallet to continue.",
    createOrg: "Create organization",
    manageOrg: "Manage organization",
    profile: "Profile",
    profileOpen: "Account",
    profileIdentity: "AI Providers (BYOC)",
    profileOrg: "Organization",
    profileSignOut: "Disconnect wallet",
    profileSignedOut: "Not connected",
  },
  org: {
    title: "Organization",
    helper:
      "Institutional workspaces are wallet-bound. Create an organization to require the full policy.",
    nameLabel: "Organization name",
    namePlaceholder: "Acme Robotics",
    create: "Create organization",
    creating: "Creating…",
    leave: "Leave organization",
    leaving: "Leaving…",
    walletRequired: "Connect a wallet before creating or leaving an organization.",
    createFailed: "Could not create the organization.",
    leaveFailed: "Could not leave the organization.",
    sandboxBody:
      "You are on Personal Sandbox. Filters are optional. Create an organization to enforce institutional policy.",
    institutionalBody:
      "You belong to an institutional network. Shield requires every mandatory filter.",
    members: "Members",
    admin: "Admin",
  },
  providers: {
    title: "Model compute",
    helper:
      "Beta includes a small hosted Gemini pool for judges. For unlimited inference, bring your own key — it stays in this browser session and is never written to Kachis storage.",
    openai: "OpenAI",
    anthropic: "Anthropic",
    gemini: "Gemini",
    custom: "Other / custom",
    configured: "Configured",
    missing: "Not set",
    seatTitle: "Wallet binding",
    betaTitle: "Kachis beta hosted",
    betaBody:
      "Shared Gemini pool for demos and judges. Not your key — Kachis pays these tokens.",
    betaReady: "{remaining} of {limit} responses left today",
    betaEmpty: "Daily beta quota used. Switch to BYOC to continue.",
    betaOffline: "Hosted Gemini is offline in this environment.",
    byocTitle: "Bring your own compute",
    byocBody:
      "Configure a provider for this tab session only. Kachis never stores or logs the key.",
    byocProvider: "Provider",
    byocCustomName: "Provider name",
    byocCustomNamePlaceholder: "e.g. Together, Fireworks, Groq…",
    byocBaseUrl: "API base URL",
    byocBaseUrlPlaceholder: "https://api.example.com/v1",
    byocBaseUrlHint: "OpenAI-compatible chat completions endpoint root.",
    byocModel: "Model id",
    byocModelPlaceholder: "Optional model id",
    byocKey: "API key",
    byocKeyPlaceholder: "Paste key — session memory only",
    byocSave: "Use for this session",
    byocClear: "Clear session key",
    byocReady: "Session key loaded · {provider}",
    byocEmpty: "No BYOC key in this session",
    byocModalTitle: "Bring your own compute",
    byocModalBody:
      "Keys stay in this browser session and are used ephemerally for inference. Closing the tab clears them.",
  },
  identity: {
    disclose: "Clearance",
    context:
      "Account bound via wallet credentials. Roles and clearance tokens remain on-device.",
  },
} as const;
