/** Canonical UI strings. Mirror `copy.md` — do not invent a second voice. */

export const copy = {
  brand: {
    name: "Kachis",
    product: "Data Shield",
  },
  input: {
    title: "Original prompt",
    helper: "Paste here. Secrets stay on this machine until you scan and settle.",
    placeholder: "Type or paste payroll, source, contracts, or internal notes…",
    paste: "Paste",
    pasteFailed: "Clipboard paste blocked — use Ctrl+V.",
    sample: "Load payroll sample",
    sampleCode: "Load code & client sample",
    sampleProse: "Load free-text sample",
    security: "Security filters",
  },
  filters: {
    pii: {
      label: "Strip identifiers",
      tooltip:
        "Masks emails, phones, SSNs, places, and named people locally (rules + on-device detector).",
    },
    financial: {
      label: "Mask financials",
      tooltip: "Redacts amounts, written scale figures, IBAN, card, routing, and account formats.",
    },
    secrets: {
      label: "Hold secrets",
      tooltip: "Blocks API keys, JWTs, and private key material locally.",
    },
    code: {
      label: "Insulate source",
      tooltip: "Hides env assignments, embedded secrets, and internal paths.",
    },
    client: {
      label: "Strip client records",
      tooltip:
        "Removes labeled CRM lines and detected organization names locally.",
    },
  },
  pack: {
    required:
      "Institutional workspaces must enable every filter before scan.",
    labels: {
      pii: "Identifiers",
      financial: "Financials",
      secrets: "Secrets",
      code: "Source",
      client: "Client",
    },
  },
  action: {
    idle: "Run Kachis Scanner",
    processing: "Scanning locally…",
    success: "Shielded",
    error: "Verification failed",
    scanning: "Scanning locally…",
    rewriting: "Insulating prompt…",
    guarding: "Insulating prompt…",
    proving: "Waiting for wallet…",
    attesting: "Recording settlement…",
    walletRequired: "Connect wallet to settle",
    walletRequiredHint: "Connect your wallet before you approve & settle the shield.",
    fundRequired: "Fund fee reserve to settle",
    fundRequiredHint:
      "Settlement needs a positive fee reserve. Faucet tNIGHT, wait for tDUST, then refresh balances. On Gero, exact tDUST may only appear in the wallet dashboard.",
    geroSettleHint:
      "Gero can connect and prove, but cannot balance contract settlements yet. Use 1AM to Approve & Settle.",
    geroBalanceUnsupported:
      "Gero cannot balance contract settlements yet. Connect 1AM with a funded fee reserve to settle.",
    proofServerUnreachable:
      "Proof server unreachable. Use 1AM (in-wallet proving), or start a local proof server on :6300 for Lace.",
    walletProvingUnavailable:
      "Wallet proving did not start. Unlock 1AM, approve the prove request, then try Approve & Settle again.",
    settleArtifactsMissing:
      "Settle keys did not load. Refresh the page and try again. If this persists, redeploy with Compact artifacts.",
    requiredPackNotAttested:
      "Required policy pack not attested. On Institutional, enable all five filters before settle. Sandbox uses a separate pack=0 contract.",
    settleFailed: "Settlement did not complete. Nothing was recorded.",
    settleLogFailed:
      "Settlement is on Preprod. Console log did not save — Confirm & Send may need a refresh after storage is fixed.",
    walletRejected: "Wallet request declined. Approve in your wallet to settle the shield.",
    reconnectWallet: "Wallet session expired. Disconnect and connect 1AM again, then retry.",
    walletBusy:
      "Wallet was still waking up. Approve the pop-up if it appears, or connect again.",
    settleBundleFailed:
      "Settle bundle failed to load. Stop the server and run npm run dev (webpack), then hard-refresh and reconnect 1AM.",
    privateStateCorrupt:
      "Stale local keys blocked settle. Close other localhost tabs, hard-refresh, reconnect 1AM, and settle again.",
    toastScanReady: "Prompt insulated",
    toastScanReadyBody: "Review the shielded text, then approve & settle.",
    toastSettlePending: "Waiting for wallet approval…",
    toastSettleOk: "Shield settled",
    toastSettleOkBody: "Receipt recorded. Confirm & send when ready.",
    toastSettleErr: "Settlement blocked",
    toastSendOk: "Sent to model",
    toastSendErr: "Send failed",
    toastPackRequired: "Enable required filters",
  },
  status: {
    shielded: "Shielded",
    pipeline: "Zero-leak path active",
    unverified: "Wallet not connected",
    localReview: "Local sandbox review — data insulated on-device",
  },
  sanitized: {
    title: "Shielded prompt",
    helper: "Watch the local rewrite, settle the shield, then send the insulated text.",
    empty: "Waiting for scanner",
    emptyHint: "Run Kachis Scanner on the left. The insulated prompt appears here word by word.",
    settle: "Approve & Settle Shield",
    settling: "Waiting for wallet…",
    confirmSend: "Confirm & Send",
    sending: "Sending…",
    sent: "Sent",
    receiptTitle: "Settlement receipt",
    receiptHash: "Commitment",
    receiptTx: "Settlement id",
    receiptLedger: "Public id",
    receiptReady: "Pack attested. Review, then send.",
  },
  response: {
    title: "Response",
    helper: "The model reply based on the shielded prompt.",
    empty: "No response yet",
    emptyHint: "Confirm & Send the shielded prompt to generate a reply.",
    emptyBeforeShield: "Scan, settle, and confirm the prompt first. The model reply appears here.",
    waiting: "Waiting for the model…",
    assistantLabel: "Kachis",
    walkthroughLabel: "Walkthrough",
    betaLabel: "Beta · Gemini",
    betaModelLabel: "Beta · Gemini · {model}",
    byocLabel: "BYOC",
    byocModelLabel: "BYOC · {provider} · {model}",
    copyReply: "Copy reply",
    copiedReply: "Copied",
    restoreNote:
      "The model only saw insulated tokens. Kachis restored real names locally for readability — secrets never left this device.",
    noModel:
      "No model path ready. Use free responses or bring your own compute.",
    error: "Request failed. The shielded prompt was not delivered.",
    fundedQuota: "{remaining}/{limit} free responses left today",
    fundedModel: "Kachis funded · Gemini",
    fundedEmpty: "0/{limit} free responses left today",
    fundedOffline: "Hosted compute offline",
    needMore: "Need more?",
    bringCompute: "Bring your own compute",
    usingByoc: "Using your compute · {provider}",
    manageByoc: "Manage compute",
    clearByoc: "Switch back to Kachis funded",
  },
  chat: {
    // Legacy keys kept for any remaining imports; prefer sanitized / response.
    title: "Response",
    subtitle: "The model only ever sees the shielded prompt.",
    userLabel: "You",
    assistantLabel: "Kachis",
    placeholderLocked: "Shield your prompt first",
    placeholderWallet: "Connect your wallet to continue",
    placeholderOpen: "",
    send: "Confirm & Send",
    emptyLocked: "Waiting for scanner",
    emptyLockedHint: "Run the scanner, settle the shield, then confirm & send.",
    emptyWallet: "Connect your wallet.",
    emptyWalletHint: "Connect on the top right, then settle the shield.",
    emptyFund: "Fee reserve required.",
    emptyFundHint:
      "Faucet tNIGHT, wait for tDUST, refresh balances, then settle the shield.",
    emptyOpen: "Ready to send",
    emptyOpenHint: "Confirm & Send the shielded prompt to the model.",
    useShielded: "Use shielded prompt",
    noModel:
      "No model path ready. Use beta quota or add a BYOC key in AI Providers for this session.",
    walkthroughLabel: "Walkthrough",
    suggestionShielded: "Confirm & Send",
    suggestionEdit: "Review insulated text",
  },
  demo: {
    nav: "Walkthrough",
    landing: "Walkthrough",
    banner:
      "You are in demo. No wallet or settlement required. Sample paste, local scan, simulated settle, canned reply.",
    loadSample: "Load sample",
    settleNote: "Walkthrough settle. No wallet or Midnight transaction ran.",
    reply:
      "Leak risk: High if this packet left the perimeter unshielded. Identifiers, bank rails, cash figures, and an export key were present in the original paste.\n\nCFO briefing (redacted)\n\n- Packet: Q3 compensation review for the board call\n- Subject: [PERSON_1] · [EMAIL_1] · [PHONE_1]\n- Tax ID: [SSN_1]\n- Banking: account [ACCOUNT_1], routing [ACCOUNT_2]\n- Comp: bonus [AMOUNT_1]; salary band [AMOUNT_2]–[AMOUNT_3]\n- Secrets: payroll export key removed ([SECRET_1])\n\nRecommendation: circulate only this insulated summary. Keep the original packet on-device; do not paste raw values into vendor models or shared docs.",
  },
  seat: {
    unbound: "Not connected",
    notConnected: "Not connected",
    verified: "Connected",
  },
  guardrails: {
    liveTitle: "Mandatory filters",
    liveHint:
      "Institutional workspaces must enable every filter before scan. Tenant-persisted policy is later.",
    seatTitle: "Workspace governance",
    seatEmpty: "No wallet connected.",
    seatLive: "Wallet connected. Role policies are later.",
  },
  rail: {
    title: "Local verification path",
    last: "Last verification",
    idle: "No local verification yet",
    ledger: "Public commitment id",
    notaryLocal: "Recorded locally. Connect a funded wallet to settle.",
    notaryServer: "Verification service reachable. Settlement still needs a funded wallet.",
    notarySettled: "Settled. Verification ran; the original stays on this machine.",
    settleFallback:
      "Settlement did not complete. The local commitment is still recorded.",
    tx: "Settlement id",
    network: "Network",
    steps: [
      {
        id: "how-paste",
        title: "Paste internally",
        body: "Source, records, and briefs stay in your sandbox. Nothing is uploaded yet.",
      },
      {
        id: "how-scan",
        title: "Run Kachis Scanner",
        body: "Sensitive spans highlight, then rewrite into insulated placeholders on this machine.",
      },
      {
        id: "how-settle",
        title: "Approve & settle",
        body: "Confirm in your wallet. The receipt proves the pack ran — without revealing the file.",
      },
      {
        id: "how-chat",
        title: "Confirm & send",
        body: "Only the insulated prompt reaches the model. Raw values stay here.",
      },
      {
        id: "how-identity",
        title: "Authenticate the member",
        body: "Corporate credentials prove role and policy without exposing the token.",
      },
    ],
  },
  tiers: {
    sandbox: {
      id: "freelancer" as const,
      pill: "Sandbox",
      badge: "Sandbox Workspace",
      description: "Individual sandbox for secure data parsing.",
      limit:
        "Approaching freelance local limit. Upgrade to an Institutional Network for company-wide custom rules, advanced regex filtering, and security compliance matrices.",
    },
    institutional: {
      id: "institutional" as const,
      pill: "Institutional",
      badge: "Institutional Network",
      description:
        "Enterprise-wide guardrail featuring custom organizational identity roots and granular workspace governance.",
    },
  },
  agent: {
    title: "Autonomous Agent Insulation",
    description:
      "Insulate machine-to-machine workflows. Protect background developer scripts, automated data analysts, and service bots from leaking proprietary records to public endpoints.",
    label: "Automate",
    badge: "SDK Gateway Active",
  },
  wallet: {
    connect: "Connect Wallet",
    verifying: "Connecting...",
    verifiedSuffix: "Organization Verified",
    identity:
      "Identity authenticated via sovereign credentials. Your private roles and cryptographic clearance tokens remain on-device.",
    disconnect: "Disconnect",
    cancel: "Cancel",
    choose: "Connect a wallet. The unshielded address is used for dApp connect.",
    modalTitle: "Connect a Wallet",
    modalEducateTitle: "What is a Wallet?",
    modalEducateAssetsTitle: "A home for your digital assets",
    modalEducateAssetsBody: "Wallets are used to send, receive, store, and display digital assets.",
    modalEducateLoginTitle: "A new way to log in",
    modalEducateLoginBody:
      "Instead of creating new accounts and passwords on every website, just connect your wallet.",
    modalGetWallet: "Get a Wallet",
    modalLearnMore: "Learn More",
    modalRecommended: "Recommended",
    modalComingSoon: "Coming soon",
    modalSupported: "Supported",
    modalDetected: "Detected",
    modalUnavailable: "Install to connect",
    modalEmpty:
      "Install 1AM and unlock it on this page. Other wallets are listed for later settle support.",
    modalApproveHint: "Approve in the wallet pop-up. It may open behind this window.",
    modalComingSoonHint: "Settle support is not ready for this wallet yet.",
    unshielded: "Unshielded",
    shielded: "Shielded",
    dust: "Fee reserve",
    dustExists: "Exists",
    dustCheckWallet: "For exact balance, check your Gero wallet / dashboard.",
    refresh: "Refresh balances",
    balancesUnavailable: "Balances unavailable",
    viewIdentity: "Open organization",
  },
  analytics: {
    leaks: "Pack coverage",
    secretsHeld: "Secrets filter hits",
    secretsHint: "Settlements with secrets pack on",
    credentials: "Explorer contract",
    settlements: "On-chain settlements",
    cycles: "Recent shielded jobs",
    quarterTitle: "Preprod ledger",
    quarterEmpty: "No on-chain settlements on Preprod yet.",
    quarterSettlements: "Settlements",
    quarterFindings: "Filter flags",
    quarterOnChain: "On-chain",
    packs: "Filters",
    trailHint:
      "Open Midnight Audit Trail for chronological settlements, commitment hashes, and policy flags.",
    sourceTitle: "Settlement source",
    sourceHelper: "Where settled jobs originated (agent, console, or ledger read).",
    packTitle: "Filter mix",
    packHelper: "How often each pack flag appears on settled Preprod commitments.",
    sequenceTitle: "Ledger sequence",
    sequenceHelper:
      "Cumulative on-chain settlements by ledger id. Timestamps may share the latest contract read.",
    sequenceY: "Cumulative settlements",
    recentTitle: "Latest on-chain",
    recentHelper: "Public commitments from the Preprod contract — original paste never appears.",
    loading: "Reading Preprod ledger…",
    emptyCharts: "No settled data to chart yet.",
    feedChain: "Preprod ledger (public)",
    feedLocal: "Live ledger unreachable — seed and local rows hidden",
    feedUnknown: "Checking live ledger…",
    feedBadgeLive: "Preprod ledger (public)",
    feedBadgeDown: "Ledger unreachable",
    feedBadgeLoading: "Reading ledger",
    emptyUnreachable:
      "Charts stay empty until the Preprod indexer returns live contract state. Local seed and walkthrough settlements are not shown.",
    openContract: "Open contract",
    openAudits: "Open audit trail",
    packCoverageHint: "Average packs enabled per settlement",
    settlementsHint: "Live Preprod only — seed and walkthrough excluded",
  },
  audits: {
    title: "Settlement register",
    helper:
      "Public commitments from the live Preprod ledger. Original text never appears here.",
    binding: "Binding",
    noPack: "No filters recorded on this settlement.",
    loading: "Reading Preprod ledger…",
    empty: "No on-chain settlements on Preprod yet.",
    emptyUnreachable:
      "Register stays empty until the Preprod indexer returns live contract state. Local seed and walkthrough settlements are not shown.",
    countLabel: "Settlements",
    openContract: "Open contract",
    openAnalytics: "Open analytics",
  },
  integrations: {
    title: "Integration Workspace",
    helper:
      "Deploy and manage the local shield across developer environments, apps, and network perimeters.",
    diagEngine: "Core environment",
    diagEngineActive: "Active",
    diagEngineBody: "Local shield engine available in this console.",
    diagEvidence: "Evidence layer",
    diagEvidenceVerified: "Verified",
    diagEvidenceWaiting: "Waiting",
    diagEvidenceBodyOn: "Public commitments reaching this console.",
    diagEvidenceBodyOff: "No agent commitments recorded yet.",
    livePhase: "Live integrations",
    livePhaseHelper: "Built and ready to deploy or track.",
    pipelinePhase: "In development & institutional pipeline",
    pipelinePhaseHelper: "Roadmapped surfaces. Same shield contract when they ship.",
    badgeOperational: "Operational",
    badgeReady: "Ready to deploy",
    badgeLaunch: "Launch ready",
    badgeConnected: "Connected & intercepting",
    badgeSetup: "Setup required",
    badgePipeline: "Pipeline · Q4 2026",
    badgeInstitutional: "Institutional pipeline · 2027",
    badgePlanned: "Planned sidecar",
    categoryDev: "Developer environments",
    categoryApps: "End-user applications",
    categoryNative: "Native UI",
    categoryMachine: "Machine-to-machine",
    categoryInfra: "Enterprise infrastructure",
    categorySystem: "System infrastructure",
    mcpTitle: "Kachis Agent (MCP)",
    mcpBody:
      "Hooks into the IDE agent loop. Shields sensitive paste before it reaches a public model. Host must call kachis_shield, send only the shielded prompt, then kachis_restore on the reply.",
    mcpCompat: "Cursor, Claude Desktop, and other MCP hosts",
    mcpAction: "Manage configuration",
    mcpHideConfig: "Hide configuration",
    extensionTitle: "Browser companion",
    extensionBody:
      "Monitors input on public AI sites. Pauses submit to shield sensitive data in the page before it leaves the browser.",
    extensionCompat: "Chrome, Brave, Edge",
    extensionAction: "Install extension",
    extensionNote:
      "Wave 1 packaging — install link will appear here when the store package is published.",
    workspaceTitle: "Protected AI Chat",
    workspaceBody:
      "Split-screen workspace on this machine. Shield paste, review the insulated remainder, settle evidence, then send to your model.",
    workspaceCompat: "This console",
    workspaceAction: "Open workspace",
    sdkTitle: "Programmatic SDK",
    sdkBody:
      "Package wrapper for automated workflows. Insulates agents, bots, and scheduled pipelines inside the execution layer.",
    sdkCompat: "Node.js, Python, Rust · @kachis/shield",
    sdkAction: "View API specs",
    sdkNote: "Published package ships after Wave 1. Today: runShield in shared/.",
    gatewayTitle: "Network gateway",
    gatewayBody:
      "Infrastructure perimeter for outbound model traffic from unmanaged devices and legacy systems across the company network.",
    gatewayCompat: "Docker, Kubernetes, Terraform",
    gatewayAction: "Request architecture brief",
    gatewayNote: "Institutional SKU after the SDK and machine seats land.",
    sidecarTitle: "Local core service",
    sidecarBody:
      "Background service that coordinates on-device shielding and evidence for every edge host. Installer and always-on sidecar come after the library path.",
    sidecarCompat: "Windows, macOS, Linux",
    sidecarAction: "View diagnostics",
    configLabel: "MCP config",
    copyConfig: "Copy",
    copiedConfig: "Copied",
    toolTitle: "Tool contract",
    toolName: "kachis_shield",
    toolInput: "Raw paste + optional pack toggles. Defaults: all five packs on.",
    toolOutput:
      "Shielded prompt plus public commitments. Original text and token map never leave the machine in this payload.",
    restoreTool: "kachis_restore",
    restoreHelper:
      "After the model replies, restore enumerated tokens on-device. Secrets stay masked unless opted in.",
    toolRule: "Send only the shielded prompt to the model — never the original paste.",
    step1Title: "Install the agent",
    step1Body:
      "From the agent folder: npm install, then npm start — or let the host start it via MCP.",
    step2Title: "Add the host config",
    step2Body:
      "Paste this into Cursor or Claude Desktop MCP settings. On Windows, set cwd to the full path of the agent folder.",
    step3Title: "Shield before the model",
    step3Body:
      "Host calls kachis_shield on the raw paste, then sends only the shielded prompt to the model. After the reply, call kachis_restore locally. Public commitments post to this console.",
    activityTitle: "Agent activity",
    activityHelper:
      "Public commitments recorded when the agent reaches this console. Original paste is never stored.",
    activityEmpty:
      "No agent shields recorded yet — start the agent and call kachis_shield.",
    // Legacy aliases
    agentTitle: "Kachis Agent (MCP)",
    agentBody:
      "Local MCP server for Cursor and Claude Desktop. The host must call kachis_shield before any model sees the paste, then kachis_restore after the reply.",
    agentStatusLive: "Operational",
    activityHash: "Commitment",
    activityMeta: "Source · status",
    libraryTitle: "Programmatic SDK",
    libraryBody:
      "Package wrapper for automated workflows. Insulates agents, bots, and scheduled pipelines.",
    companionTitle: "Browser companion",
    companionBody:
      "Monitors input on public AI sites. Shields sensitive data before it leaves the browser.",
    statusLater: "Pipeline",
    statusLive: "Operational",
  },
  landing: {
    launchApp: "Launch app",
  },
  onboarding: {
    signInTitle: "Sign in to Kachis",
    signInBody: "Connect a wallet to continue.",
    signInHint: "No password. Approve the wallet connection to continue.",
    signedIn: "Wallet connected",
    walletFirst: "Wallet-first access. Your unshielded address becomes your account id.",
    openingWorkspace: "Opening workspace…",
    verifyingAccount: "Checking your account…",
    chooseTitle: "Choose your workspace",
    chooseBody:
      "Solo workspaces stay freemium with optional filters. Institutional networks enforce full policy.",
    soloTitle: "Launch Solo Sandbox",
    soloBody:
      "For freelancers and builders. Optional filters, no forced institutional policy, immediate workspace access.",
    soloCta: "Enter sandbox",
    institutionalTitle: "Provision Institutional Node",
    institutionalBody:
      "For companies. Create an organization, assign the admin, and require every mandatory filter.",
    institutionalCta: "Provision node",
    orgNameHint: "Enter an organization name (at least 2 characters).",
    configureTitle: "Configure workspace",
    configureSoloBody: "Personal Sandbox with optional filters. No institutional policy enforced.",
    configureOrgBody: "Name the organization. You become the admin.",
    finishTitle: "Launch workspace",
    finishSoloBody: "Create your sandbox profile and open the console.",
    finishOrgBody: "Provision the institutional node, then open the console.",
    stepBack: "Previous",
    stepNext: "Next",
    stepComplete: "Launch",
    successSoloTitle: "You're in",
    successSoloBody: "Personal Sandbox is ready. Setting up your workspace next.",
    successOrgTitle: "Organization created",
    successOrgBody: "{name} is live. Setting up your institutional workspace next.",
    setupLoading: [
      { text: "Binding wallet identity" },
      { text: "Applying workspace policy" },
      { text: "Preparing secure console" },
      { text: "Opening workspace" },
    ],
    provisionSteps: [
      "Initializing core keys…",
      "Creating organization…",
      "Syncing with Midnight contract space…",
      "Applying required policy…",
      "Node status: Operational",
    ],
    provisionDone: "Organization ready. Opening console…",
    supabaseMissing:
      "Supabase is not configured. Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY, then run supabase/schema.sql.",
    upgradeTitle: "Institutional Network",
    upgradeBody:
      "Custom filters, organization members, and mandatory policy are available on an institutional node.",
    upgradeCta: "Upgrade workspace",
    locked: "Institutional",
  },
  nav: {
    workspace: "Workspace",
    security: "Security & Evidence",
    settings: "Settings",
    contextLabel: "Organization",
    sandbox: "Personal Sandbox",
    institutional: "Institutional Network",
    orgSuffix: "Network",
    connectHint: "Connect a wallet to continue.",
    createOrg: "Create organization",
    manageOrg: "Manage organization",
    profile: "Profile",
    profileOpen: "Account",
    profileIdentity: "AI Providers (BYOC)",
    profileOrg: "Organization",
    profileSignOut: "Disconnect wallet",
    profileSignedOut: "Not connected",
  },
  org: {
    title: "Organization",
    helper:
      "Institutional workspaces are wallet-bound. Create an organization to require the full policy.",
    nameLabel: "Organization name",
    namePlaceholder: "Acme Robotics",
    create: "Create organization",
    creating: "Creating…",
    leave: "Leave organization",
    leaving: "Leaving…",
    walletRequired: "Connect a wallet before creating or leaving an organization.",
    createFailed: "Could not create the organization.",
    leaveFailed: "Could not leave the organization.",
    sandboxBody:
      "You are on Personal Sandbox. Filters are optional. Create an organization to enforce institutional policy.",
    institutionalBody:
      "You belong to an institutional network. Shield requires every mandatory filter.",
    members: "Members",
    admin: "Admin",
  },
  providers: {
    title: "AI Providers",
    helper:
      "Beta includes a small hosted Gemini pool for judges. For unlimited inference, bring your own key — it stays in this browser session and is never written to Kachis storage.",
    openai: "OpenAI",
    anthropic: "Anthropic",
    gemini: "Gemini",
    custom: "Other / custom",
    configured: "Configured",
    missing: "Not set",
    betaTitle: "Kachis beta hosted",
    betaBody:
      "Shared Gemini pool for demos and judges. Not your key — Kachis pays these tokens.",
    betaReady: "{remaining} of {limit} responses left today",
    betaEmpty: "Daily beta quota used. Switch to BYOC to continue.",
    betaOffline: "Hosted Gemini is offline in this environment.",
    byocTitle: "Bring your own compute",
    byocBody:
      "Configure a provider for this tab session only. Kachis never stores or logs the key.",
    byocProvider: "Provider",
    byocCustomName: "Provider name",
    byocCustomNamePlaceholder: "e.g. Together, Fireworks, Groq…",
    byocBaseUrl: "API base URL",
    byocBaseUrlPlaceholder: "https://api.example.com/v1",
    byocBaseUrlHint: "OpenAI-compatible chat completions endpoint root.",
    byocModel: "Model id",
    byocModelPlaceholder: "Optional model id",
    byocKey: "API key",
    byocKeyPlaceholder: "Paste key — session memory only",
    byocSave: "Use for this session",
    byocClear: "Clear session key",
    byocReady: "Session key loaded · {provider}",
    byocEmpty: "No BYOC key in this session",
    byocModalTitle: "Bring your own compute",
    byocModalBody:
      "Keys stay in this browser session and are used ephemerally for inference. Closing the tab clears them.",
  },
  identity: {
    disclose: "Clearance",
    seatTitle: "Wallet binding",
    context:
      "Account bound via wallet credentials. Roles and clearance tokens remain on-device.",
  },
} as const;
